---
- name: Install general software
  become: yes
  apt:
    name: "{{ apt_softlist.common }}"
    update_cache: yes

- name: Install software for KDE
  become: yes
  apt:
    name: "{{ apt_softlist.kde }}"
  when: ansible_env.XDG_CURRENT_DESKTOP == "KDE"

- name: Install software for GNOME
  become: yes
  apt:
    name: "{{ apt_softlist.gtk }}"
  when: ansible_env.XDG_CURRENT_DESKTOP != "KDE"

- name: Install software for notebook
  become: yes
  apt:
    name: "{{ apt_softlist.note }}"
  when: ansible_form_factor == "Notebook"
