language: python
python:
  - "3.6"

env:
  - version: "2.9.*"
  - version: "2.8.*"
  - version: "2.7.*"

install:
  - pip install ansible==${version} ansible-lint

script:
  - ansible-playbook -vvv --syntax-check playbook.yml
  - ansible-lint -v playbook.yml
