---
galaxy_info:
  role_name: backlight
  author: Oleg Dolgikh
  description: Setup backlight
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu Linux
    - name: Arch Linux

dependencies: []