---
- name: Install cifs-utils
  become: yes
  package:
    name: cifs-utils

- name: Create secret file
  template:
    src: "secret.j2"
    dest: "{{ secret_file }}"
    mode: 0600
  when: nas_password | length > 0
  notify: Restart automount units

- name: Create directories for mounts
  become: yes
  file:
    path: "{{ mount_directory }}/{{ item }}"
    state: directory
  with_items: "{{ shares }}"

- name: Create mount units
  become: yes
  template:
    src: "mount.j2"
    dest: "/etc/systemd/system/{{ service_name }}.mount"
  with_items: "{{ shares }}"
  notify: Restart automount units

- name: Create automount units
  become: yes
  template:
    src: "automount.j2"
    dest: "/etc/systemd/system/{{ service_name }}.automount"
  with_items: "{{ shares }}"
  notify: Restart automount units

- name: Enable automount units
  become: yes
  systemd:
    name: "{{ service_name }}.automount"
    daemon_reload: yes
    enabled: yes
  with_items: "{{ shares }}"

- name: Create symlink to mount dir
  become: yes
  file:
    src: "{{ mount_directory }}"
    dest: "{{ ansible_user_dir }}/{{ mount_directory | basename }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
