---
galaxy_info:
  role_name: iptables
  author: Oleg Dolgikh
  description: Setup iptables
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu Linux
    - name: Arch Linux

dependencies:
  - role: install_package
    packages:
      - 'iptables-persistent'
    when: ansible_pkg_mgr == 'apt'
