---
backlight_file: "{{ '/etc/X11/Xsession.d/99backlight' if ansible_pkg_mgr == 'apt' else
                    '/etc/X11/xinit/xinitrc.d/99backlight' if ansible_pkg_mgr == 'pacman'}}"
max_brightness_file: "/sys/class/backlight/intel_backlight/max_brightness"
brightness_file: "/sys/class/backlight/intel_backlight/brightness"
command: "echo {{ brightness_value }} > {{ brightness_file }}"