---
galaxy_info:
  role_name: docker
  author: Oleg Dolgikh
  description: Install docker and docker-compose
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu Linux

dependencies: []
